version: '3.8'

services:
  
  flaskapp:
    build:
      context: .
      dockerfile: flaskapp.Dockerfile
    ports:
      - "5050:5000"
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
