apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodb-replication-policy
spec:
  replicas: 1
  selector:
    app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo-db
        image: 891376963426.dkr.ecr.us-east-1.amazonaws.com/mongo:v0.1
        ports:
        - containerPort: 27017 
          #        volumeMounts:                 
          #          - name: mongo-pvc           
          #            mountPath: /data/db       
          #      volumes:                        
          #      - name: mongo-pvc               
          #        persistentVolumeClaim:        
          #          claimName: mongo-pvc-rwx

