apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-viewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-viewer
subjects:
- kind: ServiceAccount
  name: prometheus-server # Replace with the name of Prometheus service account
  namespace: prometheus # Replace with the namespace where Prometheus is deployed

